### ISSUE TITLE
error.message contains error.stack instead

### ISSUE THREAD

**Issue by heri16** [krakenjs/zalgo-promise#2]
I am using postRobot to pass a callback function to another window. When this callback function is called with `callback(new Error('cancelled by user'))`, the Error object below is received by the parent window.

```javascript
{
message: 'Error: cancelled by user at blob:https://vault.sandbox.keyhub.app/93ee58c7-2819-4225-a67e-48be1b3abcc5:2121:38',
stack: `Error: Error: cancelled by user
   at blob:https://vault.sandbox.keyhub.app/dfa5c1b8-c661-415b-b8d5-9d920e12a7d7:2121:38
   at http://localhost:3000/static/js/bundle.js:186968:51
   at http://localhost:3000/static/js/bundle.js:186971:38
   ...`
}
```

How do I get only the original error message (just 'cancelled by user')?

**Comment by heri16** [comment]
Seems like Zalgo is wrapping errors twice?

```
new Error(new Error('cancelled by user')).message
"Error: cancelled by user"
```
```
Error('cancelled by user').message
"cancelled by user"
```

**Comment by heri16** [comment]
https://github.com/krakenjs/post-robot/issues/61
